{
 "title": "New dashboard Copy",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Payments per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n$__time(dt),\npayments\nfrom (\n  select \n  min(time) as dt,\n  count (*) as payments \n  from payments \n    group by (extract(epoch from time)/3600)::bigint*3600 \n    order by (extract(epoch from time)/3600)::bigint*3600\n    ) as foo\nwhere $__timeFilter(dt)"
    }
   ]
  },
  {
   "title": "Trustlines per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n$__time(dt),\ntrustlines\nfrom (\n  select \n  min(time) as dt,\n  count (*) as trustlines \n  from trustlines \n    group by (extract(epoch from time)/3600)::bigint*3600 \n    order by (extract(epoch from time)/3600)::bigint*3600\n    ) as foo\nwhere $__timeFilter(dt)"
    }
   ]
  },
  {
   "title": "Amount per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(dt),\n  amount\nFROM\n  (\n  SELECT\n    min(time) as dt,\n    sum (amount) as amount \n  FROM payments \n    group by (extract(epoch from time)/3600)::bigint*3600 \n    order by (extract(epoch from time)/3600)::bigint*3600\n  ) as foo\nWHERE\n  $__timeFilter(dt)"
    }
   ]
  }
 ]
}